// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package data

import (
	"database/sql"
)

type Event struct {
	ID         int32
	Name       string
	PromoUrl   sql.NullString
	LocationID sql.NullInt32
	// Repeating can be daily/weekly/monthly/etc
	Repeating sql.NullString
	Start     sql.NullTime
	End       sql.NullTime
	MenuID    sql.NullInt32
}

type EventsView struct {
	Event     string
	PromoUrl  sql.NullString
	Repeating sql.NullString
	Start     sql.NullTime
	End       sql.NullTime
	Location  string
	Longitude sql.NullString
	Latitude  sql.NullString
	Menu      sql.NullString
}

type Location struct {
	ID        int32
	Name      string
	Longitude sql.NullString
	Latitude  sql.NullString
}

type Menu struct {
	ID   int32
	Name sql.NullString
}

type MenuItem struct {
	ID   int32
	Name string
	// Recipe can be URL
	Recipe string
	Cost   sql.NullFloat64
	MenuID sql.NullInt32
}

type MenusView struct {
	Menu     sql.NullString
	MenuItem string
	Recipe   string
	Cost     sql.NullFloat64
}

type Order struct {
	ID       int32
	Created  sql.NullTime
	EventID  sql.NullInt32
	PatronID sql.NullInt32
	Till     sql.NullInt32
}

type OrderItem struct {
	ID         int32
	Quantity   sql.NullInt32
	Price      sql.NullFloat64
	OrderID    sql.NullInt32
	MenuitemID sql.NullInt32
}

type OrdersView struct {
	OrderID      int32
	Quantity     sql.NullInt32
	Price        sql.NullFloat64
	OrderDate    sql.NullTime
	MenuItem     string
	PatronName   sql.NullString
	CashierName  sql.NullString
	LocationName string
	Longitude    sql.NullString
	Latitude     sql.NullString
}

type Patron struct {
	ID        int32
	Name      sql.NullString
	Email     string
	NewsOptIn sql.NullBool
}

type PatronsView struct {
	ID        int32
	Name      sql.NullString
	Email     string
	NewsOptIn sql.NullBool
}

type Trucker struct {
	ID          int32
	Name        sql.NullString
	Job         sql.NullString
	PayRate     sql.NullFloat64
	SocialMedia string
	Deactivated sql.NullTime
}
