name: Test SQL

on:
  push:
    branches:
      - main

jobs:
  test_sql:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run script
        run: |
          sudo /etc/init.d/mysql start
          sudo mysql --user=root --password=root < schema.sql

      - name: Try export to compare
        run: |
          mysqldump -uroot -proot --compact --skip-quote-names it125_foodtruck > dump.sql


